# Generated by Django 5.1.4 on 2024-12-21 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='created_at',
        ),
        migrations.AddField(
            model_name='report',
            name='code_block',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='report_images/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lab_number',
            field=models.CharField(max_length=50),
        ),
    ]
