# Generated by Django 5.1.4 on 2024-12-22 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_report_created_at_report_code_block_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='code_block',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.CreateModel(
            name='ReportCodeBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_blocks', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='report_images/')),
                ('caption', models.CharField(max_length=255)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reports.report')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
