# Generated by Django 5.1.4 on 2024-12-22 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_remove_report_code_block_remove_report_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='workflow',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('text', 'Текст'), ('image', 'Изображение'), ('code', 'Код')], max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_images/')),
                ('image_caption', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='reports.report')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
