# Generated by Django 5.1.4 on 2024-12-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_report_workflow_reportcontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='workflow',
        ),
    ]
